// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdYPQv0Nlf6u3krhQPGw7I21pVsM10sEg',
    appId: '1:262858126186:web:8e7fefbc35e3f094886b13',
    messagingSenderId: '262858126186',
    projectId: 'codechine-2af52',
    authDomain: 'codechine-2af52.firebaseapp.com',
    storageBucket: 'codechine-2af52.firebasestorage.app',
    measurementId: 'G-SP3813P8EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATdiUG-zVxmAR7MN-Si2qgoECMGORiePg',
    appId: '1:262858126186:android:16c86e0b38f5fbd3886b13',
    messagingSenderId: '262858126186',
    projectId: 'codechine-2af52',
    storageBucket: 'codechine-2af52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Pe_5ApS24y2f3IKW1p_KLxQrnJbCCMA',
    appId: '1:262858126186:ios:34ee6feaa88ba5b1886b13',
    messagingSenderId: '262858126186',
    projectId: 'codechine-2af52',
    storageBucket: 'codechine-2af52.firebasestorage.app',
    iosBundleId: 'com.example.taskCodechine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Pe_5ApS24y2f3IKW1p_KLxQrnJbCCMA',
    appId: '1:262858126186:ios:34ee6feaa88ba5b1886b13',
    messagingSenderId: '262858126186',
    projectId: 'codechine-2af52',
    storageBucket: 'codechine-2af52.firebasestorage.app',
    iosBundleId: 'com.example.taskCodechine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdYPQv0Nlf6u3krhQPGw7I21pVsM10sEg',
    appId: '1:262858126186:web:1cc58e4d95913932886b13',
    messagingSenderId: '262858126186',
    projectId: 'codechine-2af52',
    authDomain: 'codechine-2af52.firebaseapp.com',
    storageBucket: 'codechine-2af52.firebasestorage.app',
    measurementId: 'G-GGVQFGBGLK',
  );
}
